### ISSUE TITLE
[Request]: Enhanced clipboard support

### ISSUE THREAD

**Issue by gaussandhisgun** [GeopJr/Tuba#468] opened 2023-08-31 16:59 UTC
### Describe the request

The first thing that most people do after making a screenshot is assume its in the clipboard and they can paste it wherever they want. Most of the time this is the case, even in Android of all things. This works with most browsers, [Moshidon for Android](https://github.com/LucasGGamerM/moshidon) (and, most likely, original mastodon app too), most chat apps, i think Gnome's own Chats app supports it as well - but not Tuba. Yet.

What I'm saying is, users should be able to paste [supported file formats](https://fedi.tips/how-do-i-post-images-videos-or-audio-in-mastodon-what-can-i-attach-to-a-post-how-do-i-post-gifs/) (there is a serverside check for this) into the Compose box and *know* they are going to be attached. Now they aren't.

Environment: GNOME 44.3; Arch Linux, Tuba 0.4.1 from Flatpak, Pano clipboard manager (tho it really should not matter)

Proof that this follows the GNOME HIG: [boop](https://developer.gnome.org/hig/principles.html#reduce-user-effort)

> Try to minimize the number of steps required to perform a task.

Right now, to attach a screenshot, you need to open the File tab, tap on Pick File, then pick your screenshot from the latest files *if* it is in the latest files, otherwise go to Pictures and look for it manually. This can be minimized to *one* keystroke. Or two mouse clicks. One if you know about the fact that dragging over context menus is faster.

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment] 2023-08-31 22:25
Thanks for the suggestion!

It (both paste and dnd) has been added as of #413 and will be available in the next release.

Duplicate of: #411

**Closed by GeopJr** 2023-08-31 22:25 UTC
Labels: enhancement
