### ISSUE TITLE
[Bug]: Laggy interface

### ISSUE THREAD

**Issue by imhemish** [GeopJr/Tuba#231] opened 2023-05-05 16:29 UTC
### Describe the bug

Earlier sometime ago, the app used to work normally. Now, it just lags all the time. When I scroll, it takes a while to load information, and even after loading it freezes and can't scroll. I have turned 'stream timelines' feature off in preferences, still it lags like that.

### Steps To Reproduce

Just use the app, and try to scroll

### Logs and/or Screenshots

Here is a relevant video:
[Kooha-2023-05-05-21-48-29.webm](https://user-images.githubusercontent.com/74466492/236514495-e15e4e4f-445c-4a41-ab6f-9b7ad4db4f1b.webm)

### Instance Backend

Mastodon

### Operating System

Arch Linux

### Package

Flatpak

### Troubleshooting information

os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.2.0 (production)
gtk: 4.10.3 (4.10.1)
libadwaita: 1.3.2 (1.3.1)
libsoup: 3.4.1 (3.4.0)
libgtksourceview: 5.8.0 (5.8.0)

**Comment by GeopJr** [comment] 2023-05-05 16:35
Thanks for raising this issue!

It's a duplicate of #182

as a workaround, try waiting a second until the initial load is done before scrolling / doing other network related activities

**Closed by GeopJr** 2023-05-05 16:35 UTC
Labels: bug
