### ISSUE TITLE
[Question] How do custom emojis work?

### ISSUE THREAD

**Issue by TheKrafter** [GeopJr/Tuba#622] opened 2023-10-26 16:15 UTC
Hey, I love this client and I LOVE how custom emojis work so flawlessly having those images inserted inline at the perfect size within blocks of text in posts and display names.

I'm trying to write a custom GTK4/Libadwaita client in Python for a proprietary messaging service that has custom emojis for their platform.

I was wondering, how have you implemented this system to display custom emojis in posts? I'm not hyper-familiar with GTK things, tho I would love to learn more! Pointing to the part of the code this is in would be great, but as I don't know Vala well at all an explanation of the method would be greatly appreciated!

And thanks again for this wonderful Mastodon client!

**Comment by GeopJr** [comment] 2023-10-26 18:37
Most of the magic happens here: https://github.com/GeopJr/Tuba/blob/cbf10b3bb8d1fe02d5cb0c0f56756d8fd862d2ea/src/Widgets/LabelWithWidgets.vala

It's a port from Fractal's https://gitlab.gnome.org/GNOME/fractal/-/blob/2e62541bef31a7be635309f4fe077fbef2f96f00/src/components/label_with_widgets.rs

Tuba's version has some tuba specific hacks so I'd recommend you porting it from Fractal instead, but Vala's syntax should be a lot clearer than Rust's unless you are used to it.

The way it works might be a bit complicated for newcomers to GTK & libraries but it'll definitely be a great practice and learning experience! 

Here's how it works:
- LabelWithWidgets is a generic widget with a label child and any other children provided
- You provide a string but with a placeholder where widgets will be and an array of widgets, for example you'd pass `Hi <widget> looks at this emoji <widget>` and an array with two Image widgets that will be put where `<widget>` is
- When the string gets updated (see `update_label`), LabelWithWidgets manipulates the string a bit based on whether wrap and/or ellipsize is enabled, but most importantly it replaces the placeholder with an single unicode character (which doesnt have any width)
- LabelWithWidgets overrides some widget functions (measure, size_allocate) and forwards them to the label child - so LabelWithWidgets has the same measurements as it - after calling `allocate_shapes` and `allocate_children`
- `allocate_shapes` gets the children widget sizes and creates Pango Rectangles for them and adds them to the label child
- `allocate_children` allocates the children widget sizes based on Pango attributes

I think that's pretty much it. The good thing about it is that unless it's done 100%, any bugs will be instantly visible (when implementing it I was stuck with a bug where some emojis would be in random places, that was caused by using the label's *label* insted of *text* (text is the visible text, so `hi <a href="">name</a>`'s label is `hi <a href="">name</a>` but text is `hi name`)

I'll close this so it doesn't clog the issue tracker but feel free to continue the discussion if needed!

**Closed by GeopJr** 2023-10-26 18:37 UTC

**Comment by TheKrafter** [comment] 2023-10-28 19:40
thanks!
