### ISSUE TITLE
Consider submitting Tuba for inclusion in GNOME Circle

### ISSUE THREAD

**Issue by bragefuglseth** [GeopJr/Tuba#391] opened 2023-07-19 12:49 UTC
I think Tuba is a good candidate for [GNOME Circle](https://circle.gnome.org), since it's a great app using GNOME technologies. Inclusion in GNOME Circle would give the app more exposure, and prominent contributors would qualify for membership in the GNOME Foundation. Have you considered this?

**Comment by GeopJr** [comment] 2023-07-19 21:58
I've been avoiding submitting to Circle so far *because* it would bring more exposure than I can handle at the moment, I'll reconsider it! (I already have other apps in Circle :seedling:)

**Comment by afranke** [comment] 2023-11-21 08:03
This is now [in progress](https://gitlab.gnome.org/Teams/Circle/-/issues/193).

**Comment by julianfairfax** [comment] 2024-01-02 22:10
In addition to joining Circle, it would also be nice if the app's code were moved to [GNOME World](https://gitlab.gnome.org/World). GitHub is not an open source platform, and being owned by Microsoft makes it more of a danger to open source projects, rather than a help.

**Comment by GeopJr** [comment] 2024-01-15 14:07
I want to but there's also a lot that need to be migrated gracefully:

- [ ] Pull request commit history (probably impossible): Most PRs are being squash merged, leaving behind their (usually) organized commit history and allowing us to pinpoint regressions (especially helpful on big cleanup PRs)
- [ ] CI workflows need to be re-written
- [ ] Notify any services that depend on the nightly.link links
- [ ] Make sure mirroring from GitLab works as expected
- [ ] Notify distributors & flathubbot
- [ ] Point weblate to it (might also not be possible and might have to switch to damned lies)
- [ ] And finally, apply to World

**Comment by bragefuglseth** [comment] 2024-08-24 10:16
As of now, Tuba has been approved, and will be formally included upon its next stable release.

**Comment by GeopJr** [comment] 2024-08-24 10:18
Thanks!

On that note, should I aim for a quick patch release before 47 so it makes it into the announcement or should I aim for 48?

**Comment by bragefuglseth** [comment] 2024-08-24 10:54
Do what you think is best for Tuba in terms of release consistency / QA. We’re fortunately not in a hurry 🙂

**Comment by bragefuglseth** [comment] 2024-08-24 10:59
If you’re planning to do a grand release for 47 anyways, though, I’d put out the Circle patches now. Otherwise we’ll get Tuba into Circle right at the release of 47, and have to wait for GNOME 48 to do the release. So I see what you mean regarding that.

**Comment by GeopJr** [comment] 2024-08-24 16:38
I mostly took a break from Tuba since 0.8.2 (both for myself and for circle + mastodon to catch up). There haven't been any user-facing changes merged since https://github.com/GeopJr/Tuba/compare/v0.8.2...main so I think I can do a patch, I'll prepare some stuff for adw 1.6 too. I'm afraid that if it doesn't happen now, it will be too late for 48 and will need another full review :sweat_smile:

**Comment by bragefuglseth** [comment] 2024-08-24 16:41
Go ahead then! :)

**Comment by GeopJr** [comment] 2024-08-28 19:09
https://fosstodon.org/@bragefuglseth/113030003231359426

🎺📥👣🌱

**Closed by GeopJr** 2024-08-28 19:09 UTC
