### ISSUE TITLE
[Request]: Remember my position / New Items indicator

### ISSUE THREAD

**Issue by alexmarkley** [GeopJr/Tuba#772] opened 2024-02-04 19:38 UTC
### Describe the request

As a user who likes to read every post in my Mastodon timeline, I would like to have the option for Tuba to remember my position in my home timeline, even across application restarts.

Ideally...
- My home timeline would not jump to a different position, even if the application restarts or if the host has been suspended for a long time.
- Tuba would display an indicator (perhaps in the top-right corner) with the current number of unread posts, counting down while I scroll up.

For an example of this, see Ivory (Mastodon client for macOS and iOS client).

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment] 2024-02-04 20:07
Thanks for the suggestion! Duplicate of #309 (partially), #373 and other timelines UX issues

While this is definitely something I want to add and was mentioned in Tuba's review for inclusion in GNOME Circle, due to some underlying issues with the way timelines work in tuba, I cannot currently do that. Rest assured that the priority is high but it has to wait until everything else is done!

> Tuba would display an indicator (perhaps in the top-right corner) with the current number of unread posts, counting down while I scroll up.

I'll revisit this after the above is done

> For an example of this, see Ivory (Mastodon client for macOS and iOS client).

Unfortunately, I do not have a device that can use Ivory to fully grasp the workflow

**Closed by GeopJr** 2024-02-04 20:07 UTC
Labels: enhancement
