### ISSUE TITLE
[Request]: Notifications by type

### ISSUE THREAD

**Issue by trufae** [GeopJr/Tuba#910] opened 2024-04-15 11:12 UTC
### Describe the request

Will be useful to separate the notifications by type, so you can have a different timeline for favs, retoots, posts, editions, etc.. that will allow me to have a timeline viewing only the people i follow and have notifications involved

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment] 2024-04-15 21:17
Thanks for the suggestion!

Duplicate of: #167 
Fixed by: #893

There's some stuff that needs clarification on #893 but will be merged for the next release, hopefully!

**Closed by GeopJr** 2024-04-15 21:17 UTC
Labels: enhancement
