### ISSUE TITLE
[Request]: Handle custom emojis in profile sidebar section

### ISSUE THREAD

**Issue by bragefuglseth** [GeopJr/Tuba#164] opened 2023-04-06 22:30 UTC
### Describe the request

Custom emojis are rendered properly in most of Tuba, but not in:
- the sidebar section displaying the currently logged in user
![Screenshot from 2023-04-07 00-20-38](https://user-images.githubusercontent.com/91388039/230505206-a7f50ff4-2027-4ae9-bb22-1ecec2f3a4cf.png)
- the user switcher
![Screenshot from 2023-04-07 00-28-42](https://user-images.githubusercontent.com/91388039/230505257-6ba57e27-0666-4987-9feb-3bded916f94a.png)
Custom emojis should be handled properly here as well, to avoid any visual awkwardness.

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment] 2023-04-06 22:35
Merged ~1 hour ago! (duplicate of #1)

(For context: Labels can't have images or other widgets in them. The post author names were horizontal boxes (that can't wrap). 1c015124d04b0244a4aac44318160676ff887790 ported LabelWithWidgets from Fractal that allows that, emojis should now be visible in most places, let me know if I missed something!)

**Closed by GeopJr** 2023-04-06 22:35 UTC
Labels: enhancement
