### ISSUE TITLE
[Request]: Disable or Match spell check language to toot language

### ISSUE THREAD

**Issue by DarkGhostHunter** [GeopJr/Tuba#1190] opened 2024-11-05 18:46 UTC
### Describe the request

By default, when writing, on GNOME 46/47, the spell checker will run for the user language. When doing a post in a different language, the spell checker will still use the default language.

The alternative would be to disable spell check via a config option, to avoid marking the whole text wrong.

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment] 2024-11-05 20:40
Thanks for the suggestion!

This is a duplicate of #454. The main problem, as mentioned there too, is that Mastodon supports a far more limited range of locales than libspelling. So while Mastodon supports e.g. 'German', libspelling supports 'German (Austria)', 'German (Switzerland)' and  'German (Germany)' (well, for German, there's probably a clear default but for other languages like Arabic there's wayyyyy more options).

> to disable spell check

If you right click anywhere in the text box, you can disable the spell checker or manually change the language. Tuba will remember whether the spell checker is enabled between restarts.

**Closed by GeopJr** 2024-11-05 20:40 UTC
Labels: enhancement
