### ISSUE TITLE
[Bug]: dragging to scale past a breakpoint has very bad performance

### ISSUE THREAD

**Issue by RedAuburn** [GeopJr/Tuba#1132] opened 2024-09-25 00:21 UTC
### Describe the bug

scaling the app to what is presumably the mobile breakpoint causes very poor performance

### Steps To Reproduce

scale window horizontally

### Logs and/or Screenshots

https://github.com/user-attachments/assets/59b86bba-f93c-407e-a9d0-203523a6cff9

### Instance Backend

Mastodon

### Operating System

Fedora 40

### Package

Flatpak

### Troubleshooting information

os: GNOME 46 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.8.4 (production)
gtk: 4.14.5 (4.14.4)
libadwaita: 1.5.4 (1.5.3)
libsoup: 3.4.4 (3.4.4)
libgtksourceview: 5.12.1 (5.12.1)

**Comment by GeopJr** [comment] 2024-09-25 11:50
Thanks for raising this issue!

Duplicate of #1053

**Closed by GeopJr** 2024-09-25 11:50 UTC
Labels: bug
