### ISSUE TITLE
[Request]: Collapse boost & like notifications

### ISSUE THREAD

**Issue by wjt** [GeopJr/Tuba#630] opened 2023-11-07 10:36 UTC
### Describe the request

Yesterday I tooted a toot that has been liked 32 times and boosted 43 times. Look at me, I'm a social media hotshot!

In Tuba this makes the *Notifications* tab completely unusable. I just have page after page of the same toot, with a very small line of text reading “So-and-so favorited your post”.

Elk has a nice feature (copied from Twitter I believe) where it collapses such notifications into a single row.

![image](https://github.com/GeopJr/Tuba/assets/86760/167ee78c-0983-426f-af03-48a8d6e16bb1)

This means that, even without a mentions vs notifications distinction (https://github.com/GeopJr/Tuba/issues/167, which Elk also has) the *Notifications* tab is still usable.

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by wjt** [comment] 2023-11-07 10:37
(Is there really any value in forcing people to tick a “This follows the GNOME HIG” tickybox before they file a feature request?)

**Comment by GeopJr** [comment] 2023-11-07 11:46
duplicate of #176

> (Is there really any value in forcing people to tick a “This follows the GNOME HIG” tickybox before they file a feature request?)

Probably not but it also discourages suggestions that don't match the HIG. Unsurprisingly, people have a lot of opinions about it, quoting one of Tuba's reviews:

> Pros: As the title says. It works great. Everything is snappy and smooth navigating,it was easy to set up, and feature and function works properly. \n\nCons: it's ugly, but also doesn't do well at a full screen size. Tuba was clearly designed for Linux phone. \n\nThe GNOME design philosophy is not good for apps. buttons get put in places that are annoying to go to, even if they move when resized. It breaks it's own philosophy of being out of the way by trying to condense too much \n\nSwitching accounts doesn't need to be in a drop-down, and frankly stops me from wanting to use them. These are options you want available, not hidden. \n\nThe settings and preferences are a bit too simplistic to fix the problems it has with resizing. Going from a phone sized, vertical window to full screen creates large gaps that centres the timeline and looks really bad by constraining all the text to the same sized centred timeline area. \n\nI'm by far someone cares about aesthetics all that much, but I do care about user experience, and until these specific things can be changed in the preferences I would love it.

I'm not against removing the checkbox though if it prevents newcomers from contributing though

**Closed by GeopJr** 2023-11-07 11:46 UTC
Labels: enhancement

**Comment by wjt** [comment] 2023-11-07 20:10
Fair enough if it works1

**Comment by valpackett** [comment] 2024-06-24 21:06
Any particular reason this was closed as not planned? All the discussion was about the GNOME HIG checkbox, nothing about the actual issue at hand…

Filtering (#167) is definitely a decent workaround but collapsed "N people liked/boosted $toot" notifications would still be very nice!

**Comment by GeopJr** [comment] 2024-06-24 23:53
Because it's a duplicate of #176 (it was the first sentence but you might have missed it with the wall of text after it)

Next Mastodon version does grouping client side so it's worth waiting a bit to see how it goes!
