### ISSUE TITLE
[Request]: Scheduled posts

### ISSUE THREAD

**Issue by canadaduane** [GeopJr/Tuba#738] opened 2024-01-05 21:22 UTC
### Describe the request

The Mastodon API supports scheduled posts, but not through the web app. Could Tuba support this?

https://docs.joinmastodon.org/methods/scheduled_statuses/

I believe some apps already implement scheduled posts and might serve as example implementations, such as Tusky, Fedilab, and Friendica.

2022 discussion: https://mastodon.social/@atomicpoet/109599256740575334

### Implementation Details

- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment] 2024-01-06 09:11
Thanks for raising this issue!

Duplicate of #142 
Will probably be part of #553

**Closed by GeopJr** 2024-01-06 09:11 UTC
Labels: enhancement
