### ISSUE TITLE
[Request]: Support back gesture in media lightbox

### ISSUE THREAD

**Issue by eobet** [GeopJr/Tuba#375] opened 2023-07-13 10:33 UTC
### Describe the request

On a laptop with a touchpad, you still have to move the pointer to the top left corner and tap in order to exit the media lightbox.

It would be more efficient for pure touchpad navigation if the general two finger swipe to the left would be recognized and supported as a means to go back to the timeline.

### Implementation Details

- [x] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by eobet** [comment] 2023-07-13 10:36
Even the "Gesture Improvements" Gnome Extension, with a special forward/backward App Gesture addition for Tuba could not get this working.

**Comment by eobet** [comment] 2023-07-13 18:58
Ok, this won't work with posts containing multiple images if they have to be arranged horisontally... would it be possible to enable a different gesture or arrange them vertically instead?

Right now, the media lightbox is the only thing forcing you move the cursor to the extremes of the app window to navigate out of. Basically every other common interaction you perform with the app (except for posting) can be made by keeping the cursor near the middle of the screen...

**Comment by GeopJr** [comment] 2023-07-15 01:24
There was (still is on v0.3.2) a drag gesture to dismiss it (drag the image up or down). It was removed on #326 due to issues with mobile devices triggering it on touch (which I couldn't reproduce on desktop with touch simulation).

> if the general two finger swipe to the left would be recognized and supported as a means to go back to the timeline

> Ok, this won't work with posts containing multiple images if they have to be arranged horisontally... would it be possible to enable a different gesture or arrange them vertically instead?

I'll consider drag to dismiss again but it will have to go through extensive testing on mobile first.

The Carousel is as-is (gestures, direction and all).

> Right now, the media lightbox is the only thing forcing you move the cursor to the extremes of the app window to navigate out of. Basically every other common interaction you perform with the app (except for posting) can be made by keeping the cursor near the middle of the screen...

I don't think the main view and the media viewer are comparable. The main view is a list of items, the media viewer has a single focus point (the media) and actions around it.

> a single click anywhere to close the media lightbox would probably be preferrable for the fastest navigation possible!

While more gestures are definitely nice to have, we are reaching the point where users might feel overwhelmed and perhaps scared of what action might get trigger by simply touching their touchpad or screen. There 5-6 different ways (keyboard and mouse shortcuts) to go back, the media viewer alone has horizontal drag, pinch to zoom, 2 finger swipe, (soon) double click, general drag when zoomed in to pan, mouse wheel when zoomed in & other gestures. I don't think single click to dismiss is appropriate.

**Comment by CaptainMorgan12** [comment] 2023-07-19 19:23
I think a better way to use touchpad, or touchscreen device navigation to go back to timeline is using two fingers with image shown fully zoomed out:

1. swipe two fingers down
2. closes media view
3. shows timeline where media was opened

Instead of two fingers swiping left or right since that is already used to switch between images.

The two fingers swiping down feels very natural in removing what you are looking at (like tearing a page off the notebook)

**Comment by tpikonen** [comment] 2024-01-14 18:48
Tuba 0.6 closes the media view with swipe up/down (one finger on touchscreens, two fingers on touchpad). I think this is about good as it gets, since horizontal swipes change the image.

**Comment by GeopJr** [comment] 2024-01-14 18:55
Yeah, I think we can close this now!

fixed by: #602

**Closed by GeopJr** 2024-01-14 18:55 UTC
Labels: enhancement, mediaviewer
