### ISSUE TITLE
[Bug]: Pinch to zoom gesture in image viewer does not work consistently

### ISSUE THREAD

**Issue by TriVoxel** [GeopJr/Tuba#900] opened 2024-04-12 06:30 UTC
### Describe the bug

Sometimes I can use the touchpad pinch to zoom feature to zoom an image, sometimes not.

### Steps To Reproduce

1. Click an image to enlarge
2. Use a reverse pinch gesture on your touchpad to zoom in

### Instance Backend

Mastodon

### Operating System

Fedora Silverblue

### Package

Flatpak

### Troubleshooting information

os: GNOME 46 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.7.2 (production)
gtk: 4.14.1 (4.14.1)
libadwaita: 1.5.0 (1.5.0)
libsoup: 3.4.4 (3.4.4)
libgtksourceview: 5.12.0 (5.12.0)

### Additional Context

If it isn't working, I can drag around with my mouse and sometimes get it out of this state where I can't use a zoom gesture. Not entirely sure what causes it yet, but there's a 50/50 chance touchpad gestures work when I open Tuba.

**Comment by GeopJr** [comment] 2024-04-12 11:26
Not sure if #902 #899 had something to do with it as well, I can't really reproduce it but in general you have to be very precise because there are too many gestures:

- The media viewer's swipe down to dismiss one
- The carousel's swipe horizontally to move images
- The carousel children/images' pinch to zoom and others

If while trying to pinch, you trigger the media viewer's swipe down accidentally, then that's the one that will happen

I think #902 will probably fix it, if you are keen to using devel builds, feel free to try it!

**Comment by TriVoxel** [comment] 2024-04-13 02:22
Here are steps to easily reproduce 100% of the time:

1. Click an image to open the image viewer
2. Immediately close the image using the two finger swipe down gesture
3. Repeat step 1-2 about 5-10 times. Make sure you are quick on step 2
4. Open the image once again
5. Pinch to zoom (should not work)

Workaround:

1. Double-click the image to zoom in. The gesture should work now.
2. Click and drag down to close the image viewer. The gesture should work now.

**Comment by TriVoxel** [comment] 2024-04-13 03:37
Confirmed to still be an issue in main

Tested:

os: GNOME 46 (Flatpak runtime)
prefix: /app
flatpak: true
version: main-f5bd1c9 (development)
gtk: 4.13.9 (4.13.9)
libadwaita: 1.5.0 (1.5.0)
libsoup: 3.4.4 (3.4.4)
libgtksourceview: 5.11.2 (5.11.2)

**Comment by GeopJr** [comment] 2024-04-13 15:19
I see, thanks for the reproduction, I was able to reproduce it on main but not on the PR. You also tested on main but that PR wasn't merged yet! Sorry for not being very clear about it!

Let me merge it and let me know if you can reproduce it again! (If you have cloned the repo locally, do `git pull` to get the latest version of the repo)

**Comment by TriVoxel** [comment] 2024-04-14 06:19
> I see, thanks for the reproduction, I was able to reproduce it on main but not on the PR. You also tested on main but that PR wasn't merged yet! Sorry for not being very clear about it!
> 
> Let me merge it and let me know if you can reproduce it again! (If you have cloned the repo locally, do `git pull` to get the latest version of the repo)

It's actually worse in the new PR. It still happens, but I can't get it un-stuck by double-clicking to zoom, or by dragging with left click to close the image viewer.

On a brighter note, great work with the left/right scroll for image galleries! Fantastic! Feels good.

**Comment by TriVoxel** [comment] 2024-04-14 06:22
What's odd: the rest of the gestures work perfectly fine. Scrolling left/right in the photo gallery works, scroll down to dismiss image viewer works, scroll left to right to go back in a leaflet works perfectly fine... literally all the other gestures work fine for me. I only have issues with the pinch to zoom.

**Comment by GeopJr** [comment] 2024-05-26 00:07
Could you give #955 a try? (still cant reliably reproduce it :/)

**Comment by TriVoxel** [comment] 2024-06-02 07:09
I will try to test this soon…

**Closed** 2024-06-12 16:38 UTC
Labels: bug
