### ISSUE TITLE
[BUG] Fails to launch on Librem5 with PureOS.

### ISSUE THREAD

**Issue by codemeleon** [GeopJr/Tuba#117] opened 2023-03-26 10:40 UTC
Hi,
Tuba fails to launch on Librem5 with PureOS.

```
$ flatpak run dev.geopjr.Tuba
Tuba-Message: 00:10:22.406: Application.vala:102: os: GNOME 44 (Flatpak runtime)
Tuba-Message: 00:10:22.406: Application.vala:102: prefix: /app
Tuba-Message: 00:10:22.406: Application.vala:102: flatpak: true
Tuba-Message: 00:10:22.406: Application.vala:102: version: 0.1.0 (production)
Tuba-Message: 00:10:22.406: Application.vala:102: gtk: 4.10.1 (4.10.1)
Tuba-Message: 00:10:22.406: Application.vala:102: libadwaita: 1.3.1 (1.3.1)
Tuba-Message: 00:10:22.406: Application.vala:102: libsoup: 2.74.3 (2.74.3)
Tuba-Message: 00:10:22.406: Application.vala:102: 
Tuba-Message: 00:10:22.894: SecretAccountStore.vala:11: Using libsecret v0.20.5

(dev.geopjr.Tuba:2): Tuba-ERROR : 00:10:22.917: Application.vala:121: Could not start application: user interaction failed
```

**Comment by GeopJr** [comment] 2023-03-26 15:28
Does a popup show up asking you to unlock your keyring? Could you also try opening `Passwords & keys` (`seahorse`) and see if there's anything out of the ordinary?

The popup should look like this:
![image](https://user-images.githubusercontent.com/18014039/227786096-40e31ed8-c898-430d-a294-bc064fa3f819.png)

**Comment by codemeleon** [comment] 2023-03-26 15:54
No. There is no popup.

**Comment by Newbytee** [comment] 2023-03-26 16:24
Do other application that require a keyring work? E.g. GNOME Authenticator.,

**Comment by codemeleon** [comment] 2023-03-26 17:14
Keyring window pops up at login. I installed  Authenticator. It also fails to launch. However, I have Flatpak Telegram Installed which works fine.

**Comment by GeopJr** [comment] 2023-03-26 17:21
(Telegram doesn't use keyring as far as I know.)
Are you on KDE by any chance? Do you have the following packages installed?

- `xdg-desktop-portal`
- `xdg-desktop-portal-gtk`
- `gnome-keyring`

**Comment by codemeleon** [comment] 2023-03-26 17:26
All listed packages are installed.

**Comment by GeopJr** [comment] 2023-03-26 17:41
Looks like a PureOS issue :/

- https://forums.puri.sm/t/pithos-flatpak-and-keyring/19748
- https://forums.puri.sm/t/testing-fractal-dev-version-on-the-l5/14861/14
- https://forums.puri.sm/t/issue-with-flatpak-apps-gnome-application-platform-43/19244

**Comment by Newbytee** [comment] 2023-03-26 17:42
Maybe try manually creating a default keyring using Seahorse. last time I checked you had to use a mouse to set a keyring as default in Seahorse though …

**Comment by Maryjane-ai** [comment] 2023-03-26 19:39
@codemeleon I just tested tuba from flatpak on a Librem 5 with pureOS launching both from a terminal and with the desktop icon. 

And I was prompted to unlock the keyring when the app opened for the first time. But after unlocking it, and setting up the account it worked. 

On reboot, after the account was setup in tuba, if I do not unlock the keyring, I get prompted for the keyring unlocking when opening tuba. 

So I would say create a keyring. Seahorse no longer needs a mouse.

**Comment by codemeleon** [comment] 2023-03-27 10:23
@Maryjane-ai I created "password keyring" using Seahorse. However, error is still the same. I guess I need to explore more to make it work. Thank you.

**Comment by Newbytee** [comment] 2023-03-27 10:25
> @Maryjane-ai I created "password keyring" using Seahorse. However, error is still the same. I guess I need to explore more to make it work. Thank you.

Did you set it as the default keyring?

**Comment by codemeleon** [comment] 2023-03-27 11:15
yes. Please attached image
![photo_2023-03-27_12-13-40](https://user-images.githubusercontent.com/7693569/227926350-d947a9dc-792e-4641-938b-99806a4a2fb5.jpg)

**Comment by ajira86** [comment] 2023-04-04 06:47
> yes. Please see attached image

The name doesn't matter. You have to connect a mouse to your phone, right click on the keyring (there is no touch interaction for that) and choose "Set as default" in its contextual menu.

After that, reboot your phone and try again. This worked for me :)

**Comment by codemeleon** [comment] 2023-04-04 19:23
It is default. 
![image](https://user-images.githubusercontent.com/7693569/229898526-0bc84a2c-3849-4b8b-9964-a2eae62cea06.png)

**Comment by codemeleon** [comment] 2023-04-11 16:48
For now, I am switching to Tokodon. I will check after each update that Tuba becomes functional or not.

**Comment by Newbytee** [comment] 2023-04-11 16:51
> For now, I am switching to Tokodon. I will check after each update that Tuba becomes functional or not.

This is a problem with PureOS, not Tuba.

**Comment by CaptainMorgan12** [comment] 2023-04-14 17:47
I have a way in pureos10 of replicating this bug. Tuba flatpak installed fine and the keychain popup showed as well allowing me to unlock keychain, then login to Tuba mastodon using a browser.

Steps to repeat:
1. delete the keychain and password used by tuba, for me it was saved in the login keychain, im seahorse i just deleted it using a mouse,
2. i also have a second default keychain with most of my passwords in it,
3. When it popped up the unlock keychain via Tuba launch it incorrectly pointed to a non default keychain,
4. After the deletion of that secondary keychain i am getting the exact same error, user interaction failed,

I reinstalled `flatpak repair --reinstall-all` and fault still exists. I uninstalled and purged tuba and all folders, rebooted, reinstalled tuba and the same bug exists (no keychain popup).

I remember a similar issue i had using flatpak Pika the backup app in the past where it did not unlock the correct keychain and userinteraction fault. This magically resolved after a flatpak update was pushed of the Gnome 4# Application Platform runtimes. However as i stated above with current installed and reinstalled application runtime it did not resolve the Tuba issue.

**Comment by chri2** [comment] 2023-05-04 08:41
I ended up in this issue, also, after trying to start Tuba. My observations:

* keyring is `.local/share/keyrings/Standard-Schlüsselbund.keyring` (German language setting, maybe migrated from a PinePhone)
* "Standard-Schlüsselbund" in `seahorse` is marked as default
* same error message as the initial post in this issue

I looked at my dbus using `dbus-monitor --pcap` which can be read using `wireshark` and found that Tuba seems to look for a keyring named `login`. Which neither `seahorse` showed me in its view nor did I have a file `.local/share/keyrings/login.keyring`.

Using seahorse I added a keyring named `login`. I chose an empty password by typing a `space` in the password field and deleting it with `backspace` which unlocked the `continue` button. (btw: I used the same method to delete the password on my default keyring, because I didn't want to enter it after having unencrypted my drive and logged in successfully on my Librem5.)

This created the file `.local/share/keyrings/login.keyring`.

A new start of Tuba provided me with the expected dialogue to input a server and let me authorize the client through the webinterface.

Opening `seahorse` again at this point didn't show me the `login` keyring anymore in its gui.

Looking at my Librem14 running the same software stack, but using Gnome I found that there also exists a file `login.keyring` which I cannot see in `seahorse`. On this system Tuba started without this issue.

To confirm that this works for me I
* killed all `gnome-keyring-daemon` on my Librem5
* deleted `.local/share/keyrings/login.keyring`
* started over finding the above confirmed
* shutdown the phone and restarted
* phosh login still worked
* after successful login Tuba started as expected

**Comment by codemeleon** [comment] 2023-05-04 09:32
@chri2 Thank you. I confirm that your guideline worked. I think, developer should make changes so Tuba should look for default keyring, instead of login keyring.

**Comment by CaptainMorgan12** [comment] 2023-05-04 14:28
> 

you are a genious i shoukd have caught the fact that deting the login keyring is what causes all the issues. Also the space, backspace trick again genious!! thanks tuba works again

**Closed** 2023-05-13 01:12 UTC

**Comment by GeopJr** [comment] 2023-05-13 01:20
Here's what's going on:

- Tuba (and many other apps) searches for accounts on the **default keyring**
- `gnome-keyring` < 42 [has a bug](https://gitlab.gnome.org/GNOME/gnome-keyring/-/issues/107) that assumes the default keyring is named `login`
- PureOS has renamed the default keyring to something else
- PureOS (+ debian) doesn't ship gnome-keyring >= 42 yet

There's not much I can do from my side other than prompt users to read chri2's guide (which I transferred [to the wiki](https://github.com/GeopJr/Tuba/wiki/keyring-issues)) when there's an error while searching for keys #243
