### ISSUE TITLE
[Bug]: Tuba crashes when pressing reply on a post [Mobian Trixie/L5]

### ISSUE THREAD

**Issue by baarkerlounger** [GeopJr/Tuba#998] opened 2024-06-12 13:16 UTC
### Describe the bug

Pressing the reply icon on a timeline post causes Tuba to crash.

### Steps To Reproduce

1. Click the reply icon on a timeline post

### Logs and/or Screenshots

```
(dev.geopjr.Tuba:2): Tuba-WARNING **: 14:01:58.122: Streams.vala:78: Error opening stream: Peer failed to perform TLS handshake: Error receiving data: Connection reset by peer

(dev.geopjr.Tuba:2): Tuba-WARNING **: 14:02:04.339: Streams.vala:78: Error opening stream: Could not connect to streaming.mastodon.social: Connection reset by peer

(dev.geopjr.Tuba:2): Tuba-WARNING **: 14:02:04.340: Streams.vala:118: DISCONNECTED: https://mastodon.social/api/v1/streaming?stream=direct. Reconnecting in 2 seconds.
```

### Instance Backend

Mastodon

### Operating System

Mobian Trixie

### Package

Flatpak

### Troubleshooting information

os: GNOME 46 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.7.2 (production)
gtk: 4.14.4 (4.14.1)
libadwaita: 1.5.1 (1.5.0)
libsoup: 3.4.4 (3.4.4)
libgtksourceview: 5.12.0 (5.12.0)

**Comment by GeopJr** [comment] 2024-06-12 13:19
Thanks for raising this issue!

It has been fixed by f5bd1c93f50eab09b09bca4032115fe893a0199f. It will be available in the next release! 

Duplicate of: #943

**Closed by GeopJr** 2024-06-12 13:19 UTC
Labels: bug
