### ISSUE TITLE
[Request]: UnifiedPush support

### ISSUE THREAD

**Issue by johnlpe** [GeopJr/Tuba#349] opened 2023-07-05 03:09 UTC
### Describe the request

Please add support for [UnifiedPush](https://unifiedpush.org) push notification protocol/standard.

We need push notifications, but we don’t want use centralized online service that read we all notifications, like Android has Google Firebase Messaging Service and iOS has Apple Push Notification service. UnifiedPush protcol is the solution for this. UnifiedPush is open protocol/standard for connection between online service (Application Server) → notification service (Push Server) and notification service’s client (Push Distributor) → application (End User Application). It enables the user to choose the service through he receives his push notifications.

Especially GNU/Linux on mobile is very big need of push notifications and with UnifiedPush we can fix it.

<img src="https://raw.githubusercontent.com/UnifiedPush/documentation/main/static/img/animation-flow.svg" width="300"/> <img style="float: right;" src="https://github.com/mastodon/mastodon/assets/138632900/a52dd1a5-c972-4e00-8e65-4fec1aa3a5a0" width="300" />

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [ ] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment] 2023-07-05 05:05
Thanks for raising this issue!

Duplicate of: #42

**Closed by GeopJr** 2023-07-05 05:05 UTC
Labels: enhancement

**Comment by johnlpe** [comment] 2023-07-05 05:22
> Thanks for raising this issue!
> 
> Duplicate of: #42

Sorry, that issue is named a bit badly and I didn't notice it.

**Comment by GeopJr** [comment] 2023-07-05 05:23
No problem, I'll rename it!

**Comment by johnlpe** [comment] 2023-07-05 05:26
> No problem, I'll rename it!

I think we need separate issue for notifications and push notifications (via UnifiedPush protocol).

**Comment by GeopJr** [comment] 2023-07-05 05:30
Tuba already has notifications, I'll rename it again.
