### ISSUE TITLE
[Bug]: Confusing UX with the Close Button in the Top-Right Corner of the Media Viewer

### ISSUE THREAD

**Issue by Toxblh** [GeopJr/Tuba#1100] opened 2024-09-05 21:23 UTC
### Describe the bug

Description / _Current Behavior:_
- The close button ("X") located in the top-right corner of the media viewer creates UX confusion due to its placement and the animation behavior. When viewing media (such as images or videos), the animation of the viewer gives the impression that a new window has opened. As a result, users may believe that clicking the "X" will close only the media viewer, but in reality, it closes the entire program.
 
_Expected Behavior:_
- The close button should either:
1. Close only the media viewer and return to the previous screen, or
2. Be removed entirely to prevent confusion if it is intended to close the whole application.

_Possible Solutions:_
- Modify the "X" button's functionality so that it only exits the media viewer, returning the user to the previous state instead of closing the entire app.
- Alternatively, remove the "X" button from the media viewer entirely and provide a different mechanism (e.g., a back button) to return to the main interface.

### Steps To Reproduce

Open any media (image/video) in the application.
Observe the animation as the media viewer opens.
Click the "X" button in the top-right corner.

### Logs and/or Screenshots

![image](https://github.com/user-attachments/assets/5debe96f-fbad-4b91-843b-e75e5dcfdcbd)

### Instance Backend

Mastodon

### Operating System

Linux

### Package

Flatpak

**Comment by GeopJr** [comment] 2024-09-05 21:39
Thanks for the suggestion!

This is a duplicate of #586, which I just re-opened. My comment there still stands, the close button has the same function across all instances and windows, it closes the window. And since this is part of the main window, it closes the main window.

I'll also add that it would be awkward on setups other than default GNOME. E.g. if all window controls are visible, then it will be weird that all the others work as expected but the close one doesn't.

Similarly, if they are aligned to the right, the two buttons will do the exact same thing

![image](https://github.com/user-attachments/assets/a9be541a-cbe8-4aaa-bbb5-c5596ce24c4a)

Overall, if this is such big of an issue, I'd rather opt in into removing the window controls completely in the media viewer than have them not act as they are supposed to.

**Closed by GeopJr** 2024-09-05 21:39 UTC
Labels: duplicate, enhancement, mediaviewer
