### ISSUE TITLE
[Request]: Closing media by clicking outside area

### ISSUE THREAD

**Issue by heldderarbeit** [GeopJr/Tuba#450] opened 2023-08-20 15:39 UTC
### Describe the request

One Thing I like about Telegram and Element / Schildichat: When you are inside the Media Viewer, clicking outside the image closes the image. I propose the same behaviour for Tuba.

That would look like this:

![Screenshot from 2023-08-20 17-31-42](https://github.com/GeopJr/Tuba/assets/4840355/64670b92-0607-48f0-9737-254b073b3e72)

Clicking on an area outside the border of the image would exit the Media Viewer.

That would solve a problem for me: Being a long-time Telegram/Element user, I'm conditioned to press the close button to exit the Media Viewer, but in Tuba it just exits the application itself instead. Maybe being able to close images by clicking the outside area is a fair middle ground.

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by GeopJr** [comment] 2023-08-21 05:38
Thanks for raising this issue!

Duplicate of #148

**Closed by GeopJr** 2023-08-21 05:38 UTC
Labels: enhancement
