### ISSUE TITLE
[Bug]: Cannot update my profile picture or profile banner

### ISSUE THREAD

**Issue by shellyvolante** [GeopJr/Tuba#414] opened 2023-07-26 14:10 UTC
### Describe the bug

When attempting to update either my profile picture or profile banner, clicking on the pencil does nothing.  

### Steps To Reproduce

Go to profile image / profile banner pencil in profile
Click
Observe nothing happening

### Logs and/or Screenshots

```
<paste your logs here>
```

### Instance Backend

Mastodon

### Operating System

Ubuntu 23.04

### Package

Flatpak

### Troubleshooting information

os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: 0.4.0 (production)
gtk: 4.10.4 (4.10.3)
libadwaita: 1.3.3 (1.3.2)
libsoup: 3.4.2 (3.4.2)
libgtksourceview: 5.8.0 (5.8.0)

### Additional Context

Ubuntu 23.04

**Comment by GeopJr** [comment] 2023-07-26 14:14
Thanks for raising this issue!

I'm going to need some logs, run `flatpak run dev.geopjr.Tuba`, go to your profile, click the pencil icon and paste here any warning, error or critical logs that might have popped up!

**Comment by GeopJr** [comment] 2023-09-16 15:47
Let me know if you are still experiencing this

**Comment by uninsane** [comment] 2023-09-24 23:24
i see the same symptoms on NixOS/sway with Tuba 0.4.1. in my case, a "fix" is to run Tuba as follows:
```
GDK_DEBUG=no-portals dev.geopjr.Tuba
```

Tuba itself didn't output anything interesting even with `G_MESSAGES_DEBUG=all dev.geopjr.Tuba`. i click the pencil over my avatar which should open a FileDialog and aside from this log message it acts as though i didn't click any action:
```
Tuba-WARNING **: 23:12:55.929: ProfileEdit.vala:444: Couldn't get the result of FileDialog for ProfileEdit: Dismissed by user
```

although `GDK_DEBUG=no-portals` fixes this, i don't see this problem with other GTK4 apps like Dino, Komikku, or Tangram. `ps | grep portal` shows that i have the following xdg portals running:
- `xdg-desktop-portal`
- `xdg-desktop-portal-gtk`
- `xdg-desktop-portal-wlr`
- `xdg-document-portal`
- `xdg-permission-store`

i'm not able to test against tuba 0.5.0 because my gtk4/adwaita version is too old (gtk 4.10.4, adwaita 1.3.5). but i tested against the latest rev which builds and observed this same behavior. 38aeeb11c84971260880ec7744908824287fae7e. i see this behavior when creating a new post with media, as well (it too uses FileDialog):
```
AttachmentsPage.vala:320: Couldn't get the result of FileDialog for AttachmentsPage: Dismissed by user
```

**Comment by GeopJr** [comment] 2023-09-24 23:55
I'm going to need your troubleshooting information. About > Troubleshooting > Debugging Information as well as your installation method.

Here's where it happens on filedialog: https://gitlab.gnome.org/GNOME/gtk/-/blob/main/gtk/gtkfiledialog.c#L781-L783

It looks pretty ok to me. Tuba catches the error but since it can happen both when the user cancels the dialog and when the dialog is deleted (DELETE_EVENT) it doesn't show it to the user.

It's difficult to pinpoint where exactly the issue resides with the info at hand - especially with it being an older version of GTK.

Could you give the gnome portal a try too? (even though the gtk one should be enough already) `xdg-desktop-portal-gnome`

Otherwise I'll attempt recreating your environment tomorrow to further debug it

**Comment by uninsane** [comment] 2023-09-25 00:29
> About > Troubleshooting > Debugging Information
```
os: NixOS 23.11 (Tapir)
prefix: /nix/store/rwd44fjmpf7m0d533iv459s9j8kkmffa-tuba-0.4.1
flatpak: false
version: 0.4.1 (production)
gtk: 4.10.4 (4.10.4)
libadwaita: 1.3.5 (1.3.5)
libsoup: 3.4.2 (3.4.2)
libgtksourceview: 5.8.0 (5.8.0)
```

> your installation method.
```sh
nix run 'nixpkgs#tuba'
```

i tried installing `xdg-desktop-portal-gnome`, but it does not run on sway.

**Comment by GeopJr** [comment] 2023-09-28 00:53
I had trouble setting up a NixOS+Sway box but I couldn't reproduce it on other distros with sway. Could you give the following a try / read?

- https://togithub.com/NixOS/nixpkgs/issues/239886
- https://discourse.nixos.org/t/xdg-desktop-portal-not-working-on-wayland-while-kde-is-installed/20919/5
- https://togithub.com/NixOS/nixpkgs/issues/206630#issuecomment-1565046441

From the looks of it there's some cases that cause issues with the portals on NixOS.

From Tuba's side I don't see anything wrong, for example on the profile editor:

https://github.com/GeopJr/Tuba/blob/7db4ac227a8250ed69ef67bca00d2a58cc07aea0/src/Dialogs/ProfileEdit.vala#L219-L250

It fails on the callback `chooser.open.end`, gets caught and logged on line 247. The Nix pkg for Tuba also looks alright to me.

**Comment by uninsane** [comment] 2023-09-28 22:12
@GeopJr thanks for digging into that! i seem to mostly already be following the recommendations in those links... but i should have thought to check the syslog first:

after trying to open the file dialog in Tuba, this is logged:
```
$ journalctl --user -u xdg-desktop-portal
Sep 28 21:35:51 desko .xdg-desktop-po[3439]: Backend call failed: Message recipient disconnected from message bus without replying
```

actually, `xdg-desktop-portal-gtk` just crashed, and that's what `xdg-desktop-portal` is complaining about here:
```
$ journalctl --user -u xdg-desktop-portal-gtk
Sep 28 21:35:49 desko systemd[3361]: Started Portal service (GTK/GNOME implementation).
Sep 28 21:35:51 desko systemd-coredump[3457364]: [🡕] Process 3457335 (.xdg-desktop-po) of user 1000 dumped core.
...
Stack trace of thread 3457335:
                                                 #0  0x00007f5402ba5710 _gtk_file_system_model_set_filter (libgtk-3.so.0 + 0x1a5710)
                                                 #1  0x00007f5402b9b3cc operation_mode_set (libgtk-3.so.0 + 0x19b3cc)
                                                 #2  0x00007f5402b9bcc1 gtk_file_chooser_widget_map (libgtk-3.so.0 + 0x19bcc1)
                                                 #3  0x00007f5402439411 g_closure_invoke (libgobject-2.0.so.0 + 0x17411)
                                                 #4  0x00007f540244c07f signal_emit_unlocked_R.isra.0 (libgobject-2.0.so.0 + 0x2a07f)
                                                 #5  0x00007f540245331d g_signal_emit_valist (libgobject-2.0.so.0 + 0x3131d)
                                                 #6  0x00007f540245359f g_signal_emit (libgobject-2.0.so.0 + 0x3159f)
                                                 #7  0x00007f5402d60fd2 gtk_widget_map (libgtk-3.so.0 + 0x360fd2)
                                                 #8  0x00007f5402ad8ac0 gtk_box_forall (libgtk-3.so.0 + 0xd8ac0)
                                                 #9  0x00007f5402b25baf gtk_container_map (libgtk-3.so.0 + 0x125baf)
                                                 #10 0x00007f5402439600 _g_closure_invoke_va (libgobject-2.0.so.0 + 0x17600)
                                                 #11 0x00007f54024532e7 g_signal_emit_valist (libgobject-2.0.so.0 + 0x312e7)
                                                 #12 0x00007f540245359f g_signal_emit (libgobject-2.0.so.0 + 0x3159f)
                                                 #13 0x00007f5402d60fd2 gtk_widget_map (libgtk-3.so.0 + 0x360fd2)
                                                 #14 0x00007f5402d77bb0 gtk_window_map (libgtk-3.so.0 + 0x377bb0)
                                                 #15 0x00007f5402b662de gtk_dialog_map (libgtk-3.so.0 + 0x1662de)
                                                 #16 0x00007f54024394d0 g_closure_invoke (libgobject-2.0.so.0 + 0x174d0)
                                                 #17 0x00007f540244c07f signal_emit_unlocked_R.isra.0 (libgobject-2.0.so.0 + 0x2a07f)
                                                 #18 0x00007f540245331d g_signal_emit_valist (libgobject-2.0.so.0 + 0x3131d)
                                                 #19 0x00007f540245359f g_signal_emit (libgobject-2.0.so.0 + 0x3159f)
                                                 #20 0x00007f5402d60fd2 gtk_widget_map (libgtk-3.so.0 + 0x360fd2)
                                                 #21 0x00007f5402d6e752 gtk_window_show (libgtk-3.so.0 + 0x36e752)
                                                 #22 0x00007f54024394d0 g_closure_invoke (libgobject-2.0.so.0 + 0x174d0)
                                                 #23 0x00007f540244c07f signal_emit_unlocked_R.isra.0 (libgobject-2.0.so.0 + 0x2a07f)
                                                 #24 0x00007f540245331d g_signal_emit_valist (libgobject-2.0.so.0 + 0x3131d)
                                                 #25 0x00007f540245359f g_signal_emit (libgobject-2.0.so.0 + 0x3159f)
                                                 #26 0x00007f5402d5a976 gtk_widget_show (libgtk-3.so.0 + 0x35a976)
                                                 #27 0x000000000040c294 handle_open (.xdg-desktop-portal-gtk-wrapped + 0xc294)
                                                 #28 0x00007f5401716a3a ffi_call_unix64 (libffi.so.8 + 0x7a3a)
                                                 #29 0x00007f5401715935 ffi_call_int (libffi.so.8 + 0x6935)
                                                 #30 0x00007f5401716518 ffi_call (libffi.so.8 + 0x7518)
                                                 #31 0x00007f5402439c7c g_cclosure_marshal_generic (libgobject-2.0.so.0 + 0x17c7c)
                                                 #32 0x00007f54024394d0 g_closure_invoke (libgobject-2.0.so.0 + 0x174d0)
                                                 #33 0x00007f540244c3a6 signal_emit_unlocked_R.isra.0 (libgobject-2.0.so.0 + 0x2a3a6)
                                                 #34 0x000000000041e4ab _xdp_impl_file_chooser_skeleton_handle_method_call (.xdg-desktop-portal-gtk-wrapped + 0x1e4ab)
                                                 #35 0x00007f54025af535 g_dbus_interface_method_dispatch_helper (libgio-2.0.so.0 + 0x12c535)
                                                 #36 0x00007f5402594b58 call_in_idle_cb (libgio-2.0.so.0 + 0x111b58)
                                                 #37 0x00007f5402337d7f g_main_context_dispatch (libglib-2.0.so.0 + 0x5dd7f)
                                                 #38 0x00007f5402338158 g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0x5e158)
                                                 #39 0x00007f540233840f g_main_loop_run (libglib-2.0.so.0 + 0x5e40f)
                                                 #40 0x000000000040ac77 main (.xdg-desktop-portal-gtk-wrapped + 0xac77)
                                                 #41 0x00007f5402117ace __libc_start_call_main (libc.so.6 + 0x23ace)
                                                 #42 0x00007f5402117b89 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x23b89)
                                                 #43 0x000000000040ada5 _start (.xdg-desktop-portal-gtk-wrapped + 0xada5)
```

i suppose if Tuba's doing something very unusual with the filter that could be worth checking, but this looks like a bug in the gtk/portal at this point. nixos is in the process of [updating GNOME 44 -> 45](https://github.com/NixOS/nixpkgs/pull/247766), which will bring with it both a gtk, xdg-desktop-portal and libadwaita update, and allow us to update to the latest Tuba.

perhaps it makes sense to sit on this and i can try again/dig deeper after that update merges? realistic timeline for that is maybe a month since big updates like this go through staging though. i'll try to remember about it, but do feel free to ping me in case i don't.

**Comment by GeopJr** [comment] 2023-09-30 03:15
The filter is also very basic but I wouldn't doubt that it might be the cause of the issue

https://github.com/GeopJr/Tuba/blob/1fb6dcd8b7bd1a307c862304dfb7389991048c0e/src/Dialogs/ProfileEdit.vala#L76-L83

As a last second check, could you give right-clicking an attachment and selecting Save As a try? It also uses the portal and FileDialog but doesn't have filters

> realistic timeline for that is maybe a month since big updates like this go through staging though. i'll try to remember about it, but do feel free to ping me in case i don't.

I'll ping you! Thanks for the debugging!

**Comment by uninsane** [comment] 2023-10-01 18:46
@GeopJr indeed, the "Save Media" file dialog **works**: it opens, i can navigate directories, and the resulting saved media is valid.

furthermore, disabling the ProfileEdit filter does allow the dialog to open where it didn't previously. though i didn't test actually changing my profile icon. i disabled the filter on the 0.4.1 release by just removing the `default_filter = filter` line in ProfileEdit.vala:

```sh
sed -i '/default_filter = filter/d' src/Dialogs/ProfileEdit.vala
```

**Comment by uninsane** [comment] 2023-11-24 21:47
this is fixed for NixOS by the update to Gnome 45 (linked earlier). it solves the issue for Tuba 0.4.1 and the issue does not reappear when i upgrade to Tuba 0.5.0.

**Comment by gregorni** [comment] 2023-11-25 21:20
I don't know if my issue is related to this, but the app crashes for me if  I try to edit my profile. When the pencil button is clicked, the app freezes for a second, then crashes. No warnings or errors in the terminal, I don't know why.

**Comment by GeopJr** [comment] 2023-11-25 23:24
If you are using Nix, make sure you are fully up-to-date
If you are not using Nix, open a new issue with the troubleshooting information!

**Comment by GeopJr** [comment] 2023-11-28 22:09
Closing this, thanks for the all the dubgging and keeping me up-to-date uninsane!

Future readers: Update xdg-desktop-portal-gtk to >= 1.15
Ubuntu users, the portal is not on stable yet, you can get it from https://launchpad.net/ubuntu/+source/xdg-desktop-portal-gtk but you are on your own.

**Closed by GeopJr** 2023-11-28 22:09 UTC
Labels: bug, info needed
