### ISSUE TITLE
[Request]: Zoomed media UX

### ISSUE THREAD

**Issue by eobet** [GeopJr/Tuba#369] opened 2023-07-11 14:54 UTC
### Describe the request

The media lightbox/darkbox has a very bare bones UX.

For example:

* You can't double click on it to toggle zoom.
* You can't click on the background to close it out.

It took me quite some time to notice the very tiny zoom icon in the bottom right corner too, and if you're into keystroke analysis, using it is quite an operation (with the very small target increasing  the cost).

### Implementation Details

- [ ] This should be an option in settings.
- [ ] This should be only available to some fediverse backends. (Include which ones on the above field).
- [x] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).

**Comment by eobet** [comment] 2023-07-11 15:38
Noticed that the original core issue I posted about was a duplicate of this (but the two UX pain points I describe actually don't have anything to do with the touchpad per se):

https://github.com/GeopJr/Tuba/issues/264

**Comment by GeopJr** [comment] 2023-07-11 17:11
Thanks for raising this issue!

> The media lightbox/darkbox has a very bare bones UX.

The design of the media viewer is close to [Loupe](https://flathub.org/apps/org.gnome.Loupe) (the soon-to-be default image viewer on GNOME) & [Fractal](https://flathub.org/apps/org.gnome.Fractal) so users have a similar experience between them. If there are more concerns or suggestions (apart from the ones listed in the OP) I'd love to hear them but if they are too far off Loupe's or Fractal's I'll probably have to decline.

> You can't double click on it to toggle zoom.

I'll see about this but it's a bit tricky as there are zoom steps. Should double click zoom in one step or more? Should double clicking again zoom in another step or zoom out?

FWIW, Loupe toggles fullscreen on double click.

> You can't click on the background to close it out.

duplicate of #148

> It took me quite some time to notice the very tiny zoom icon in the bottom right corner too

Would changing the background to something lighter than #000 on dark mode help distinguish the floating buttons?

> if you're into keystroke analysis, using it is quite an operation (with the very small target increasing the cost).

I'm not, would you mind elaborating?

> Noticed that the original core issue I posted about

If the original issue was about pinch-to-zoom in general, Tuba has that. The linked issue is about it not matching Loupe's 1:1

**Comment by eobet** [comment] 2023-07-11 20:28
Keystroke analysis is breaking down each step of an interaction into it's basic parts and measuring where the user spends most of their time.

I don't think backgrounds or even the size of those zoom buttons would help, because even if that reduces the search step (where the user looks for the button), the move step is still very long (especially in a narrow window docked to the side of the desktop, the cursor has to be moved a very long way since the user's eyes and cursor are probably focused more to the middle of the display), and then you have to click that very small area (which is increasingly difficult in proportion to how long the mouse cursor had to travel).

Placing the zoom buttons centered under the image would be better, but then they might not be in the same place depending on the aspect ratio of the image.

Anyway, I'd settle for one zoom step for the double click, which is why I said "zoom toggle". Different zoom steps is an advanced feature which I would reserve for those zoom buttons.

Together with clicking in the background to close the lightbox, a double click to zoom in, another to zoom out, would eliminate all of the searching and most of the mouse travel in a keystroke analysis.

**Comment by GeopJr** [comment] 2023-07-13 02:50
> Keystroke analysis is breaking down each step of an interaction into it's basic parts and measuring where the user spends most of their time.

> I don't think backgrounds or even the size of those zoom buttons would help, because even if that reduces the search step (where the user looks for the button), the move step is still very long (especially in a narrow window docked to the side of the desktop, the cursor has to be moved a very long way since the user's eyes and cursor are probably focused more to the middle of the display), and then you have to click that very small area (which is increasingly difficult in proportion to how long the mouse cursor had to travel).

> Placing the zoom buttons centered under the image would be better, but then they might not be in the same place depending on the aspect ratio of the image.

Thanks for the info!

FWIW, there are buttons to go back/forwards on the left side when there are multiple attachments open. Centering, while possible, it probably won't look good when the navigation buttons are visible.

While I understand your concern, matching Loupe (the soon-to-be default image viewer on GNOME) and Fractal *should* decrease the help test by providing a familiar pattern

(screenshot of Loupe)
![image](https://github.com/GeopJr/Tuba/assets/18014039/b242f3ce-593b-47a9-b515-f5bfc29b9de1)

Perhaps providing more shortcuts might be a better middle ground (<kbd>ctrl</kbd>+<kbd>+</kbd>, <kbd>ctrl</kbd>+<kbd>MouseWheelUp</kbd> (and double clicking of course))?

**Comment by eobet** [comment] 2023-07-13 07:28
There is one very important difference between the screenshot you posted and what I'm seeing in Tuba today:

There a large, black circles behind the plus and minus buttons making them much larger. On my desktop, the background in the Tuba lightbox is 100% black, rendering those circles invisible which effectively shrinks down the button sizes to being uncomfortably small.

**Comment by eobet** [comment] 2023-07-13 10:03
You can see how mine looks in the video I posted to the issue I linked in my first reply here.

Depending on my laptop auto brightness, it's very, very dark.

I'm using Nobara from their default Gnome variant, so it is my understanding that this is the default Gnome look and feel. If this is a system default design, and there is a better place to provide feedback, I'd be interested in learning about it. The Gnome Gitlab is quite intimidating.

**Comment by LukaszH77** [comment] 2023-07-13 10:29
Mine was so bright compared to yours, because I was using the light style. With the dark style on, the buttons are still visible, but definitely not as good as they were before.

![obraz](https://github.com/GeopJr/Tuba/assets/121253127/dcb8a9c5-5bf1-455a-8146-ca88baa4a341)

**Closed** 2023-07-17 17:33 UTC
Labels: enhancement
